name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  GO_VERSION: '1.21'
  BUN_VERSION: '1.0.0'

jobs:
  # =============================================================================
  # BACKEND TESTS
  # =============================================================================
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: backend/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: backend
          args: --timeout=5m

      - name: Run unit tests
        run: go test ./tests/unit/... -v -race -coverprofile=coverage.out

      - name: Run integration tests
        run: go test ./tests/integration/... -v

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: backend/coverage.out
          flags: backend
          name: backend-coverage

  # =============================================================================
  # FRONTEND TESTS
  # =============================================================================
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test:run

      - name: Run tests with coverage
        run: bun run test:coverage

      - name: Build frontend
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: alpine/dist
          retention-days: 7

  # =============================================================================
  # BUILD BACKEND
  # =============================================================================
  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [backend-test]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" -o server ./cmd/server

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend/server
          retention-days: 7

  # =============================================================================
  # DEPLOY (Optional - uncomment when ready)
  # =============================================================================
  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: [backend-build, frontend-test]
  #   if: github.ref == 'refs/heads/main'
  #   environment: production
  #
  #   steps:
  #     - name: Download backend binary
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: backend-binary
  #         path: ./backend
  #
  #     - name: Download frontend dist
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: frontend-dist
  #         path: ./frontend
  #
  #     - name: Deploy to VPS via SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USERNAME }}
  #         key: ${{ secrets.VPS_SSH_KEY }}
  #         script: |
  #           cd /var/www/app
  #           ./deploy.sh

  # =============================================================================
  # DOCKER BUILD (Optional)
  # =============================================================================
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false  # Set to true when Docker Hub secrets are configured
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
